name: dart_util_box
description: Dart utility and extension library.
version: 1.0.2
homepage: https://github.com/JakMar17/dart_extension

maintainers:
  - Jakob Marusic

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
